schemalister/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin

from getschema import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('oauth_response/', views.oauth_response, name='oauth_response'),
    path('schema/<str:schema_id>/', views.view_schema, name='view_schema'),
    path('export/<str:schema_id>/', views.export, name='export'),
    path('logout/', views.logout, name='logout'),
    path('job_status/<str:schema_id>/', views.job_status),
    path('loading/<str:schema_id>/', views.loading),
    path('delete_schema/<str:schema_id>/', views.delete_schema, name='delete_schema'),
    path('auth_details/', views.auth_details),
]

getschema/forms.py
from django import forms
from django.forms import ModelForm

class LoginForm(forms.Form):
	environment = forms.CharField(required=False);
	access_token = forms.CharField(required=False)
	instance_url = forms.CharField(required=False)
	org_id = forms.CharField(required=False)
	include_field_usage = forms.BooleanField(required=False)
	include_managed_objects = forms.BooleanField(required=False)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Salesforce.com Schema Lister</title>
		<meta name="keywords" content="salesforce, salesforce.com, force.com, schema, schemalister, sfschema metadata, api, metadata api" /> 
  		<meta name="description" content="Build a list of objects, fields and field attributes from your Salesforce Org" />
  		<meta name="author" content="Ben Edwards (ben@edwards.nz)" />
  		<meta charset="UTF-8" />

  		{% block css %}{% endblock %}
  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-18288189-24', 'auto');
		  ga('send', 'pageview');

		</script>
		{% block scripts %}{% endblock %}
	</head>	

	<body>

		{% if request.GET.noheader != '1' %}

			<!-- Static navbar -->
	      	<nav class="navbar navbar-default">

		        <div class="container-fluid">

		          	<div class="navbar-header">
		            	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			              	<span class="sr-only">Toggle navigation</span>
			              	<span class="icon-bar"></span>
			              	<span class="icon-bar"></span>
			              	<span class="icon-bar"></span>
		            	</button>
		          	</div>

		          	<div id="navbar" class="navbar-collapse collapse">

		          		<ul class="nav navbar-nav navbar-left">
		          			<li>
		          				<a href="/" style="padding:5px;">
		          					<img src="{% static 'images/logo-small.png' %}" alt="Schema Lister" border="0" />
		          				</a>
		          			</li>
		          			<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
		              		<li>
		            			<a href="https://cloudtoolkit.co" target="_blank">Salesforce Toolkit</a>
		            		</li>
		            	</ul>

		            	<ul class="nav navbar-nav navbar-right">
							<li>
								<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="padding-top:12px;">
									<input type="hidden" name="cmd" value="_s-xclick" />
									<input type="hidden" name="hosted_button_id" value="9J3KBL2Q4ZUS4" />
									<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
									<img alt="" border="0" src="https://www.paypal.com/en_NZ/i/scr/pixel.gif" width="1" height="1" />
								</form>
							</li>
		              		<li>
		              			<a href="https://github.com/benedwards44/schemalister" target="_blank">Source Code</a>
		              		</li>
		              		<li>
		              			<a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
		              		</li>
		              		<li>
		              			<a href="#">
		              				<img src="{% static 'images/i-icon.png' %}" data-toggle="modal" data-target="#infoModal" />
		              			</a>
		              		</li>
		            	</ul>

		          	</div><!--/.nav-collapse -->

		        </div><!--/.container-fluid -->

		    </nav>

			<div class="clear"></div>

			<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
				<div class="modal-dialog small_dialog">
			    	<div class="modal-content">
			      		<div class="modal-header">
			        		<button type="button" class="close" data-dismiss="modal">
			        			<span aria-hidden="true">&times;</span>
			        			<span class="sr-only">Close</span>
			        		</button>
			        		<h3 class="modal-title" id="apiModalLabel">
			        			Salesforce Schema Lister
			        		</h3>
			      		</div>
			      		<div class="modal-body">
			        		<p>
			        			For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@edwards.nz">ben@edwards.nz</a>.
			        		</p>
			        		<p>
			        			I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
			        		</p>
			        		<p>
			        			If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
			        			<a href="https://cloudtoolkit.co" target="_blank">https://cloudtoolkit.co</a>
			        		</p>
			      		</div>
			      		<div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					    </div>
			    	</div>
			  	</div>
			</div>

		{% endif %}

		<div class="col-md-12">
			{% block content %}{% endblock %}
		</div>

	</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-6 col-md-offset-3{% endif %}">

		<h1>Salesforce Schema Lister</h1>
		<p>
			This tool uses the Salesforce Metadata API to build a list of objects, fields and field attributes from within your Salesforce Org.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool.
		</p>
		<div class="alert alert-warning alert-dismissible text-center" role="alert">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			Help keep <strong>Salesforce Schema Lister</strong> free! Please donate to support development and Heroku running costs.
			Any value is appreciated!
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="padding-top:12px;">
				<input type="hidden" name="cmd" value="_s-xclick" />
				<input type="hidden" name="hosted_button_id" value="9J3KBL2Q4ZUS4" />
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
				<img alt="" border="0" src="https://www.paypal.com/en_NZ/i/scr/pixel.gif" width="1" height="1" />
			</form>
		</div>
		<div class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<strong>Note:</strong>
			This application uses multiple API calls to your Salesforce Org to retrieve metadata and execute the logic it needs to run. Each Salesforce Org has a 24 hour limit of API calls it can make, and may break other integrations if you exceed this limit.
			<br/><br/>
			Also, please note the <strong>Description</strong> field isn't included in the REST API, so cannot be included in the report.
		</div>
		
		<table id="login_table">

			<form action="." method="POST" onsubmit="hideTable();" oncomplete="showTable();" id="loginForm"> 

				{% csrf_token %}

				<table class="login_table">

					<tr>
						<td colspan="2" style="color:#ff6600;font-weight:bold;">
							<h2>Select Options</h2>
						</td>
					</tr>

					{% if login_form.errors or login_form.non_field_errors %}
						<tr>
							<td colspan="2">
								<div role="alert" class="alert alert-danger">
									{{ login_form.errors}} <br/>
									{{ login_form.non_field_errors }}
								</div>
							</td>
						</tr>
					{% endif %}

					{% if messages %}
						<tr>
							<td colspan="2">
								<div role="alert" class="alert alert-danger">
								    {% for message in messages %}
								    	{{ message }}<br/>
								    {% endfor %}
							    </div>
							</td>
						</tr>
					{% endif %}

					<tr>
						<td width="200">
							<label for="id_environment">Environment</label>
						</td>
						<td width="200">
							<select id="id_environment" name="environment" class="form-control">
								<option value="Production">Production</option>
								<option value="Sandbox">Sandbox</option>
							</select>
						</td>
					</tr>

					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>

					<tr>
						<td colspan="2" style="text-align:center;height:50px;">
							<input type="submit" value="Login to Salesforce with OAuth" />
						</td>
					</tr>

				</table>

				<div class="loading">
					<div style="float:left;">
						<img src="{% static 'images/loading.gif' %}" alt="Loading" title="Loading" />
					</div>
					<div style="float:left;margin-left:20px;">
						<h1 style="font-size:1.5em;margin-top:20px;">Accessing Salesforce...</h1>
						<p>Logging in with OAuth 2.0</p>
					</div>
				</div>

			</form>

		</table>

	</div>

{% endblock %}

templates/loading.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-6 col-md-offset-3{% endif %}">

		<h1>Salesforce Schema Lister</h1>
		<p>
			This tool uses the Salesforce Metadata API to build a list of objects, fields and field attributes from within your Salesforce Org.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool.
		</p>
					
		<div class="loading-components">

			<div style="float:left;">
				<img src="{% static 'images/loading.gif' %}" alt="Loading" title="Loading" />
			</div>

			<div style="float:left;margin-left:20px;">
				<h1 style="font-size:1.5em;margin-top:20px;">Querying objects and fields...</h1>
				<p>This can take a few minutes.</p>
			</div>

		</div>

		<div class="alert alert-danger error" role="alert" style="display:none;">
			<p>
				There was an error processing your request: <i class="error_message"></i>
				<br/><br/>
				Please <a href="/{% if request.GET.noheader == '1' %}?noheader=1{% endif %}">return</a> to the home page and try again.
			</p>
		</div>

	</div>

	<script>
 		window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/job_status/{{ schema.random_id }}',
			    type: 'get', //this is the default though, you don't actually need to always mention it
			    success: function(resp) 
			    {
					console.log('Job Response', resp);
			        if (resp.status == 'Finished')
			        {
			        	window.location = '/schema/{{ schema.random_id }}/{% if request.GET.noheader == "1" %}?noheader=1{% endif %}';
			        } 
			        else if (resp.status == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.error);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
			    }
			});
    	}, 3000);
	</script>

{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block content %}

	<div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-6 col-md-offset-3{% endif %}">

		<h1>Salesforce Schema Lister</h1>
		<p>
			Successfully logged out of Salesforce and Schema Lister
		</p>

		<iframe src="https://{{ instance_prefix }}.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

		<script>
			setTimeout(function () {
	       		window.location.href = "/";
	    	}, 3000);
		</script>

	</div>
{% endblock %}

templates/oauth_response.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<div class="{% if request.GET.noheader == '1' %}col-md-12{% else %}col-md-6 col-md-offset-3{% endif %}">

		<h1>Salesforce Schema Lister</h1>
		<p>
			This tool uses the Salesforce Metadata API to build a list of objects, fields and field attributes from within your Salesforce Org.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool.
		</p>
					
		<table id="login_table">

			<form action="." method="POST" id="loginForm"> {% csrf_token %}

				<table class="login_table">

					{% if messages %}

						<tr>
							<td colspan="2">
								<div role="alert" class="alert alert-danger">
								    {% for message in messages %}
								    	{{ message }}<br/>
								    {% endfor %}
							    </div>
							</td>
						</tr>
						
					{% endif %}

					{% if not error %}

						<h2>Logged in as:</h2>

						<tr>
							<td width="150">
								<strong>Username:</strong>
							</td>
							<td>
								{{ username }}
							</td>
						</tr>

						<tr>
							<td width="150">
								<strong>Organisation:</strong>
							</td>
							<td>
								{{ org_name }}
							</td>
						</tr>

						<tr>
							<td width="150">
								&nbsp;
							</td>
							<td>
								<div class="checkbox">
									<label>
										{{ login_form.include_managed_objects }} Include Managed Package Objects
									</label>
								</div>
							</td>
						</tr>

						<tr>
							<td width="150">
								&nbsp;
							</td>
							<td>
								<div class="checkbox">
									<label>
										{{ login_form.include_field_usage }} Include field usage?
									</label>
								</div>
								<p>
									When this is checked, the Schema Lister will run queries to determine metadata where each field is used (eg. Workflows, Apex, Page Layouts etc). Takes substantially longer to run.
								</p>
							</td>
						</tr>

						<tr>
							<td colspan="2"></td>
						</tr>

						<tr>
							<td colspan="2" style="text-align:center;height:50px;">
								<input type="submit" name="logout" value="Logout" onclick="showLogout();" oncomplete="hideLogout();" />
								<input type="submit" name="get_schema" value="Get Schema" onclick="hideTable();" oncomplete="showTable();" />
							</td>
						</tr>

					{% else %}

					<tr>
						<td colspan="2" width="500">
							<div role="alert" class="alert alert-danger">
								<strong>Error:</strong> {{ error_message }}
							</div>
						</td>
					</tr>

					<tr>
						<td colspan="2" width="500">
							Please go <a href="/">back</a> and try again.
						</td>
					</tr>

					{% endif %}

				</table>

				<div class="loading">
					<div style="float:left;">
						<img src="{% static 'images/loading.gif' %}" alt="Loading" title="Loading" />
					</div>
					<div style="float:left;margin-left:20px;">
						<h1 style="font-size:1.5em;margin-top:20px;">Querying objects and fields...</h1>
						<p>This can take a few minutes.</p>
					</div>
				</div>

				<div class="logging_out">
					<div style="float:left;">
						<img src="{% static 'images/loading.gif' %}" alt="Loading" title="Loading" />
					</div>
					<div style="float:left;margin-left:20px;">
						<h1 style="font-size:1.5em;margin-top:20px;">Logging out...</h1>
						<p>Revoking OAuth token.</p>
					</div>
				</div>

				<div style="display:none;">
					{{ login_form.environment.as_hidden }}
					{{ login_form.access_token.as_hidden }}
					{{ login_form.instance_url.as_hidden }}
					{{ login_form.org_id.as_hidden }}
				</div>

			</form>

		</table>

	</div>

{% endblock %}

templates/schema.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">

        <div class="col-md-6">
            <h1>Salesforce Schema Lister</h1>
        </div>

        <div class="col-md-6 text-right">
            <a href="{% url 'export' schema_id=schema.random_id %}?singleTab=1">
                <button class="btn btn-warning" style="margin-top:20px;">Export to XLSX (Single Tab)</button>
            </a>
            &nbsp;
            <a href="{% url 'export' schema_id=schema.random_id %}">
                <button class="btn btn-warning" style="margin-top:20px;">Export to XLSX (Multi Tab)</button>
            </a>
        </div>

    </div>

    <div class="row">

        <div class="col-md-12">

            <hr/>

            <p>
                See the objects and fields printed below for the Org: <strong>{{ schema.org_name }}</strong> ({{ schema.org_id }}) <br/><br/>
            </p>

            {% if schema.include_field_usage %}
                <div class="alert alert-info alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Note: </strong>&nbsp;The Field Usage isn't entirely accurate for things like Apex and VisualForce. The field matching is based on whether or not the <em>field name only</em> exists in the content of the Apex or VisualForce. This means for a field of the same API name that exists on multiple objects, the app will return that this field could be used in classes and pages, whereas in fact it might not. That's why fields like <strong>Id</strong> and <strong>Name</strong> will deceptively appear in a lot of code.
                </div>
            {% endif %}

            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

                <div class="panel panel-default">

                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="collapsed">
                                Jump to Object
                            </a>
                        </h4>
                    </div>

                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            {% for object in schema.sorted_objects %} 
                                <a href="#{{ object.api_name }}" class="object_link">{{ object.label }}</a> <span class="object_link">|</span> 
                            {% endfor %}
                        </div>
                    </div>

                </div>

            </div>

            {% for object in schema.sorted_objects %}

                <a name="{{ object.api_name }}"></a>
                <h2>{{ object.label }} ({{ object.api_name }})</h2>

                <table class="table table-hover">

                    <thead>
                        <tr>
                            <th width="{% if schema.include_field_usage %}12%{% else %}16%{% endif %}">Field Label</th>
                            <th width="{% if schema.include_field_usage %}12%{% else %}16%{% endif %}">API Name</th>
                            <th width="{% if schema.include_field_usage %}12%{% else %}16%{% endif %}">Type</th>
                            <th width="{% if schema.include_field_usage %}12%{% else %}16%{% endif %}">Help Text</th>
                            <th width="{% if schema.include_field_usage %}16%{% else %}18%{% endif %}">Formula</th>
                            <th width="{% if schema.include_field_usage %}16%{% else %}18%{% endif %}">Attributes</th>
                            {% if schema.include_field_usage %}
                                <th width="20%">Field Usage</th>
                            {% endif %}
                        </tr>
                    </thead>

                    <tbody>

                    {% for field in object.sorted_fields %}
                        <tr>
                            <td>{{ field.label }}</td>
                            <td>{{ field.api_name }}</td>
                            <td>{{ field.data_type|linebreaks }}</td>
                            <td>{% if field.help_text %}{{ field.help_text|linebreaks }}{% endif %}</td>
                            <td>{{ field.formula|default_if_none:""|linebreaks }}</td>
                            <td>{{ field.attributes|default_if_none:"" }}</td>
                            {% if schema.include_field_usage %}
                                <td>{{ field.field_usage_display|safe }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}

                    </tbody>

                </table>

                <br/>

            {% endfor %}

        </div>

    </div>

    <a href="#" class="back-to-top">Back to Top</a>

{% endblock %}